version: "3.8"

services:
  bank-service-configserver:
    image: bank-service-configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bank-services

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      bank-services:

  discovery-server:
    image: discovery-server:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 300s
    environment:
      #      SPRING_APPLICATION_NAME: discovery-server
      SPRING_APPLICATION_NAME: discovery-server
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
  #      SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED: false

  customer-service:
    image: customer-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 300s
    environment:
      SPRING_APPLICATION_NAME: customer-service
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8070/eureka/

  account-service:
    image: account-service:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
      - discovery-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 300s
    environment:
      SPRING_APPLICATION_NAME: account-service
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8070/eureka/

  loan-service:
    image: loan-service:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 300s
    environment:
      SPRING_APPLICATION_NAME: loan-service
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8070/eureka/

  card-service:
    image: card-service:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 300s
    environment:
      SPRING_APPLICATION_NAME: card-service
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8070/eureka/

  gatewayserver:
    image: gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - bank-services
    depends_on:
      - bank-service-configserver
      - discovery-server
      - customer-service
      - account-service
      - loan-service
      - card-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 40s
        max_attempts: 5
        window: 400s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://bank-service-configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8070/eureka/

networks:
  bank-services: